name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_2 }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NG_CLI_ANALYTICS: "ci"
  GITHUB_API_URL: "https://api.github.com"

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Build with Maven
      run: mvn -B package -DskipTests --file SpringBoot/Konex/pom.xml
    - name: Build with Angular
      run: |
        npm run ng analytics off --prefix Angular/Konex/
        npm install --prefix Angular/Konex/
        npm run build --prefix Angular/Konex/
    #Zipping the directory dir into dir.zip:
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r konex-app.zip Angular/Konex/dist/konex-app
    - name: validate zip file
      run: |
        ls .
        ls Angular/Konex/dist/
    - name: setup semantic-release
      run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github -D
    - name: release
      run: npx semantic-release@21.0.2
    
