name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    environment: ACTIONS_ENV
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN_2 }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      GITHUB_API_URL: ${{ vars.GH_API_URL }}
      PUBLISH_ARTIFACT: ${{ vars.PUBLISH_ARTIFACT }}
      DEBUG_MODE: ${{ vars.DEBUG_MODE }}
      COMMIT_PUSH: ${{ vars.COMMIT_PUSH }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Set up Elixir 1.14.3 and Otp 25
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.3'
        otp-version: '25'
    
    - name: setup semantic-release
      run: npm install -g semantic-release @semantic-release/exec @semantic-release/changelog @semantic-release/github -D
    
    - name: release
      run: npx -p @semantic-release/changelog -p @semantic-release/exec semantic-release
      
    - name: Validate conditions
      if: ${{ env.DEBUG_MODE == 'true' }}
      run: |
        echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}"
        echo "PUBLISH_ARTIFACT=${{ env.PUBLISH_ARTIFACT }}"
        echo "CONDITION not EQ RELEASE_VERSION=${{ env.RELEASE_VERSION != '' }}"
        echo "CONDITION EQ RELEASE_VERSION=${{ env.RELEASE_VERSION == '' }}"
        echo "CONDITION TRUE PUBLISH_ARTIFACT=${{ env.PUBLISH_ARTIFACT == 'true' }}"
        echo "CONDITION FALSE PUBLISH_ARTIFACT=${{ env.PUBLISH_ARTIFACT == 'false' }}"
        echo "GITHUB_API_URL=${{ env.GITHUB_API_URL }}"
        echo "COMMIT_PUSH=${{ env.COMMIT_PUSH }}"
        echo "DEBUG_MODE=${{ env.DEBUG_MODE }}"
        echo "FILE_VERSION_TAG_EXISTS=${{ env.FILE_VERSION_TAG_EXISTS }}"

    - name: Set variables From VERSION-TAG.env
      if: ${{ hashFiles('VERSION-TAG.env') != '' }}
      run: |
        VER=$(cat VERSION-TAG.env)
        echo "$VER"
        echo "RELEASE_VERSION=$VER" >> $GITHUB_ENV

    - name: Set variables From git tag command if VERSION-TAG.env not exists
      #if: ${{ hashFiles('VERSION-TAG.env') == '' }}
      run: echo "RELEASE_VERSION=$(git tag | sort --version-sort | tail -n1)"
      # >> $GITHUB_ENV

    - name: Install Mix dependencies
      if: ${{ ( env.PUBLISH_ARTIFACT == 'true' ) }}
      run: mix deps.get && mix deps.compile
      working-directory: Elixir/Konex
      env:
        SKIP_GIT_HOOKS: 'true'
    
    - name: Run Mix tests
      if: ${{ ( env.PUBLISH_ARTIFACT == 'true' ) }}
      run: mix test
      working-directory: Elixir/Konex

    - name: Upgrade mix.exs
      if: ${{ ( env.COMMIT_PUSH == 'true' ) || ( env.PUBLISH_ARTIFACT == 'true' ) }}
      run: sed -i 's/@version \".*\"/@version "${{ env.RELEASE_VERSION  }}"/g' mix.exs
      working-directory: Elixir/Konex

    # testing
    - name: Commit And Push version
      if: ${{ ( env.COMMIT_PUSH == 'true' ) || ( env.PUBLISH_ARTIFACT == 'true' ) }}
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        push-branch: main
        commit-message: '[skip release] Upgrade version to ${{ env.RELEASE_VERSION }}'
        force-add: "true"
        files: Elixir/Konex/mix.exs
        name: Release Bot
        email: bbatist@bancolombia.com.co

    - name: Publish to HEX
      if: ${{ ( env.PUBLISH_ARTIFACT == 'true' ) }}
      run: mix hex.publish --replace --yes
      working-directory: Elixir/Konex
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
