name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  SECRETS_VARS: ${{ toJson(secrets) }}

permissions:
  contents: read # for checkout

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Setup Node.js
      #uses: actions/setup-node@v2
      #with:
      #    node-version: 'lts/*'
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Build with Maven
      run: mvn -B package -DskipTests --file SpringBoot/Konex/pom.xml
    - name: setup semantic-release
      run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
    - name: release
      run: npx semantic-release@21.0.2
